-- Check Medical_Record table schema
USE MEDCONNECT_DB;
GO

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Medical_Record'
ORDER BY ORDINAL_POSITION;
GO

-- Expected result for 'detail' column:
-- COLUMN_NAME: detail
-- DATA_TYPE: nvarchar
-- CHARACTER_MAXIMUM_LENGTH: -1 (means MAX)
-- IS_NULLABLE: YES

