package se1961.g1.medconnect.enums;

    public enum Speciality {

        NHI("Nhi"),
        REGENERATIVE_MEDICINE("Y học tái tạo (Tự kỷ bại não, Tế bào gốc)"),
        SCIENTIFIC_RESEARCH("Nghiên cứu khoa học"),
        CARDIOLOGY("Tim mạch"),
        INTERVENTIONAL_CARDIOLOGY("Can thiệp tim mạch"),
        OBSTETRICS_GYNECOLOGY("Sản phụ khoa"),
        GYNECOLOGY("Phụ khoa"),
        OBSTETRICS("Sản khoa"),
        DIGESTIVE_SURGERY("Ngoại Tiêu hoá"),
        NEUROLOGY("Thần kinh"),
        ENDOCRINOLOGY("Nội tiết"),
        INTERNAL_MEDICINE("Nội tổng quát"),
        RESPIRATORY("Hô hấp"),
        ORTHOPEDIC_SURGERY("Ngoại chấn thương chỉnh hình"),
        DIGESTIVE_ENDOSCOPY("Nội Tiêu hoá - Nội soi"),
        REHABILITATION("Phục hồi chức năng"),
        NEONATOLOGY("Sơ sinh"),
        MUSCULOSKELETAL("Cơ xương khớp"),
        COSMETIC_SURGERY("Phẩu thuật thẩm mỹ"),
        ORTHOPEDIC_SURGERY_GENERAL("Phẫu Thuật chỉnh hình"),
        IMAGING("Chẩn đoán hình ảnh"),
        DENTAL_MAXILLOFACIAL("Răng - Hàm - Mặt"),
        CRITICAL_CARE("Hồi sức - Cấp cứu"),
        ANESTHESIA("Gây mê hồi sức"),
        NUCLEAR_MEDICINE("Y học hạt nhân"),
        BIOCHEMISTRY_TEST("Xét nghiệm hoá sinh"),
        PEDIATRIC_HEMATOLOGY_BLOOD("Nhi Huyết học - Truyền máu"),
        PEDIATRIC_RESPIRATORY("Nhi Hô hấp"),
        PEDIATRIC_ENDOCRINOLOGY_GENETIC("Nhi Nội tiết - Chuyển hoá di truyền"),
        PSYCHIATRY("Tâm thần"),
        PSYCHOLOGY("Tâm lý"),
        ENT("Tai - Mũi - Họng"),
        ASTHMA_IMMUNOLOGY("Hen - Dị ứng miễn dịch"),
        BREAST_DISEASE("Bệnh lý Vú"),
        INTERNAL_CARDIOLOGY("Nội Tim mạch"),
        EXTERNAL_CARDIOLOGY("Ngoại Tim mạch"),
        GENERAL_HEALTH_CHECK("Khám sức khỏe tổng quát"),
        GENERAL_PRACTICE("Đa khoa"),
        CARDIOTHORACIC_SURGERY("Phẫu thuật Tim Mạch - Lồng Ngực"),
        TESTING("Xét nghiệm"),
        NUTRITION("Dinh dưỡng"),
        VACCINATION("Tiêm chủng vắc xin"),
        DERMATOLOGY("Da liễu"),
        ONCOLOGY_RADIOTHERAPY("Ung bướu-Xạ trị"),
        PEDIATRIC_NEPHROLOGY_URINARY("Nhi Thận - Tiết niệu"),
        INFECTIOUS_DISEASE("Truyền nhiễm"),
        PEDIATRIC_NEUROLOGY("Nhi Thần kinh"),
        COSMETIC("Thẩm mỹ"),
        PHARMACY("Dược"),
        HEMATOLOGY("Huyết học"),
        ANESTHESIA_PAIN("Gây mê - điều trị đau"),
        OPHTHALMOLOGY("Mắt"),
        UROLOGY("Tiết niệu"),
        DIGESTIVE("Tiêu hóa"),
        NEUROSURGERY("Ngoại Thần kinh"),
        INTERNAL_NEUROLOGY("Nội Thần kinh"),
        THYROID_DISEASE("Bệnh lý tuyến giáp"),
        INTERNAL_NEPHROLOGY_URINARY("Nội Thận - Tiết niệu"),
        ANATOMICAL_PATHOLOGY("Giải phẫu bệnh"),
        ANDROLOGY("Nam khoa"),
        REPRODUCTIVE_ASSISTANCE("Hỗ trợ sinh sản"),
        INTERNAL_RESPIRATORY("Nội Hô hấp"),
        TRADITIONAL_MEDICINE("Y học cổ truyền"),
        PEDIATRIC_CARDIOLOGY("Nhi Tim mạch"),
        INTERNAL_MUSCULOSKELETAL("Nội Cơ Xương Khớp"),
        MICROBIOLOGY_TEST("Xét nghiệm vi sinh"),
        PEDIATRIC_SURGERY("Ngoại nhi"),
        EXTERNAL_NEPHROLOGY_URINARY("Ngoại Thận - Tiết niệu"),
        MEDICAL_GENETICS("Di truyền y học"),
        MOLECULAR_CELL_BIOLOGY("Sinh học phân tử và tế bào"),
        LIVER_BILIARY_PANCREAS("Gan - Mật - Tụy"),
        HISTOLOGY_EMBRYOLOGY("Mô học - Phôi thai học"),
        PEDIATRIC_DIGESTIVE_LIVER("Nhi Tiêu hóa - Gan mật"),
        PEDIATRIC_NUTRITION("Nhi Dinh dưỡng"),
        MOLECULAR_IMMUNOLOGY("Miễn dịch học phân tử"),
        REHABILITATION_FUNCTION("Phục hồi chức năng"),
        MAXILLOFACIAL_TRAUMA("Chấn thương chỉnh hình hàm mặt"),
        COSMETIC_DENTISTRY("Nha khoa Thẩm mỹ"),
        PSYCHOLOGY_PSYCHIATRY("Tâm lý và Tâm thần"),
        PEDIATRIC_DIGESTIVE("Tiêu hóa Nhi"),
        GENETICS_HEMATOLOGY_RARE("Di truyền – Huyết học và Bệnh hiếm"),
        HEMATOLOGY_ONCOLOGY_RARE("Bệnh lý huyết học, ung thư huyết học - Bệnh hiếm"),
        NUTRITIONAL_SUPPORT("Dinh Dưỡng"),
        IMMUNOLOGY_ALLERGY("Miễn dịch dị ứng"),
        CLINICAL_ALLERGY("Dị ứng miễn dịch lâm sàng"),
        TISSUE_BANK("Ngân hàng mô"),
        CELL_PRODUCTION("Sản xuất tế bào"),
        QUALITY_CONTROL("Kiểm soát chất lượng"),
        BLOOD_TRANSFUSION("Huyết học - Truyền Máu"),
        CLINICAL_PSYCHOLOGIST("Chuyên gia tâm lý lâm sàng");

        private final String displayName;

        Speciality(String displayName) {
            this.displayName = displayName;
        }

        public String getDisplayName() {
            return displayName;
        }
    }
