const mockDoctors = [
  {
    id: 1,
    name: 'BS. Barry Alen',
    specialty: 'Tim mạch',
    experience: 15,
    rating: 4.9,
    patients: 1200,
    avatar: '/assets/avatar-mockup/Barry-Alen.jpg',
    specialtyValue: 'tim-mach',
    licenseId: 'BS-12345',
    phone: '0901234567',
    status: 'active',
    description: 'Chuyên gia tim mạch với hơn 15 năm kinh nghiệm trong điều trị bệnh lý tim mạch.',
    education: 'Đại học Y Hà Nội',
    certifications: ['Chứng chỉ Tim mạch nội khoa', 'Chứng chỉ Can thiệp mạch vành']
  },
  {
    id: 2,
    name: 'BS. Brian May',
    specialty: 'Nội khoa',
    experience: 12,
    rating: 4.8,
    patients: 980,
    avatar: '/assets/avatar-mockup/Brian-May.jpg',
    specialtyValue: 'noi-khoa',
    licenseId: 'BS-23456',
    phone: '0902345678',
    status: 'active',
    description: 'Bác sĩ nội khoa chuyên điều trị các bệnh lý nội tiết và tiêu hóa.',
    education: 'Đại học Y Dược TP.HCM',
    certifications: ['Chứng chỉ Nội khoa', 'Chứng chỉ Nội tiết']
  },
  {
    id: 3,
    name: 'BS. Ching Quin',
    specialty: 'Nhi khoa',
    experience: 10,
    rating: 4.7,
    patients: 850,
    avatar: '/assets/avatar-mockup/Ching-Quin.jpg',
    specialtyValue: 'nhi-khoa',
    licenseId: 'BS-34567',
    phone: '0903456789',
    status: 'active',
    description: 'Chuyên gia nhi khoa với tâm huyết chăm sóc sức khỏe trẻ em.',
    education: 'Đại học Y Hà Nội',
    certifications: ['Chứng chỉ Nhi khoa', 'Chứng chỉ Nhi sơ sinh']
  },
  {
    id: 4,
    name: 'BS. Harvard Doc',
    specialty: 'Sản phụ khoa',
    experience: 18,
    rating: 4.9,
    patients: 1500,
    avatar: '/assets/avatar-mockup/Harvard-Doc.jpg',
    specialtyValue: 'san-phu-khoa',
    licenseId: 'BS-45678',
    phone: '0904567890',
    status: 'active',
    description: 'Bác sĩ sản phụ khoa giàu kinh nghiệm trong chăm sóc thai sản.',
    education: 'Đại học Y Dược TP.HCM',
    certifications: ['Chứng chỉ Sản phụ khoa', 'Chứng chỉ Siêu âm sản khoa']
  },
  {
    id: 5,
    name: 'BS. John Mayer',
    specialty: 'Ngoại khoa',
    experience: 20,
    rating: 5.0,
    patients: 1800,
    avatar: '/assets/avatar-mockup/John-Mayer.jpg',
    specialtyValue: 'ngoai-khoa',
    licenseId: 'BS-56789',
    phone: '0905678901',
    status: 'active',
    description: 'Chuyên gia ngoại khoa với kỹ thuật phẫu thuật tiên tiến.',
    education: 'Đại học Y Hà Nội',
    certifications: ['Chứng chỉ Ngoại khoa', 'Chứng chỉ Phẫu thuật nội soi']
  },
  {
    id: 6,
    name: 'BS. Karen Sama',
    specialty: 'Thần kinh',
    experience: 14,
    rating: 4.8,
    patients: 1100,
    avatar: '/assets/avatar-mockup/Karen-Sama.jpg',
    specialtyValue: 'than-kinh',
    licenseId: 'BS-67890',
    phone: '0906789012',
    status: 'active',
    description: 'Bác sĩ thần kinh chuyên điều trị các bệnh lý về não và thần kinh.',
    education: 'Đại học Y Dược TP.HCM',
    certifications: ['Chứng chỉ Thần kinh', 'Chứng chỉ Đột quỵ']
  },
  {
    id: 7,
    name: 'BS. Taylor Swift',
    specialty: 'Da liễu',
    experience: 11,
    rating: 4.6,
    patients: 920,
    avatar: '/assets/avatar-mockup/Taylor-Swift.jpg',
    specialtyValue: 'da-lieu',
    licenseId: 'BS-78901',
    phone: '0907890123',
    status: 'active',
    description: 'Chuyên gia da liễu với kinh nghiệm điều trị các bệnh da liễu.',
    education: 'Đại học Y Hà Nội',
    certifications: ['Chứng chỉ Da liễu', 'Chứng chỉ Phẫu thuật thẩm mỹ da']
  },
  {
    id: 8,
    name: 'BS. Tim Cook',
    specialty: 'Mắt',
    experience: 16,
    rating: 4.9,
    patients: 1350,
    avatar: '/assets/avatar-mockup/Tim-Cook.jpg',
    specialtyValue: 'mat',
    licenseId: 'BS-89012',
    phone: '0908901234',
    status: 'active',
    description: 'Bác sĩ nhãn khoa chuyên điều trị các bệnh về mắt.',
    education: 'Đại học Y Dược TP.HCM',
    certifications: ['Chứng chỉ Nhãn khoa', 'Chứng chỉ Phẫu thuật mắt']
  }
];

export default mockDoctors;
